### ISSUE TITLE
HTML5 form input type: date validation fails

### ISSUE THREAD

**Issue by renejackowski** [Bloke/zem_contact_reborn#11]
When setup a form with the HTML5 input type="date" and you are e.g. on iPhone with native datepicker, the date won’t be validated. After submit ZCR says »Required field missing«, even though the date is in there. This is NOT Txp’s prefs (posted / archive dates) related.

TXP: 4.5.7
ZCR: 4.5.0.0

**Comment by Bloke** [comment]
Hmmph, still not fixed huh? Sorry.

Would you please supply me with an example contact form that you tried, so I can set it up on my server. I don't have an iPhone so I'll have to beg someone to test it out!

**Comment by renejackowski** [comment]
You’ve got mail

**Comment by philwareham** [comment]
@renejackowski could you post your code here in the issue instead, I can check the iPhone implementation then. Thanks!

**Comment by renejackowski** [comment]
@philwareham Could I send you an email, too? It’s an server account…

**Comment by Bloke** [comment]
If you could send Phil an email, that'd be brilliant, thanks. He can relay any results to me or suggest fixes. I'm iChallenged so can only try and emulate what happens by using browser inspector tools.

**Comment by renejackowski** [comment]
Yes, sure. I only need his email address ;)

**Comment by philwareham** [comment]
@bloke forward the email on to me and I can converse with René.

**Comment by renejackowski** [comment]
Best way.

**Comment by renejackowski** [comment]
@bloke @philwareham Wish you all a nice weekend, closed ;o)
