### ISSUE TITLE
class attribute bug

### ISSUE THREAD

**Issue by philwareham** [Bloke/zem_contact_reborn#14]
If you set the class attribute on tags to `class=""` you'd expect no class attribute to be added to the tags in HTML. Instead you get the empty `class=""` appearing in markup, which is not very desirable.

Need some logic which omits the class attribute altogether if a user states `class=""` on the tag.

**Comment by Bloke** [comment]
It's worse than that: sometimes you also get `class=" some-class"` with a leading space, grrr.

I've just conditioned myself to ignore it and silently gnash my teeth for the time being until we can use the improved tag building tools and `join_qs()` in the next Txp. Then it'll all go away for good.

But if it bothers you I can put conditional logic round every instance now.

**Comment by philwareham** [comment]
It does bother me, sorry! :)

**Comment by Bloke** [comment]
Fixed in 3be4cfb6bf77c8e6c2c7e36b9b43255c1bdb95bc
