### ISSUE TITLE
Beta of latest version

### ISSUE THREAD

**Issue by philwareham** [Bloke/zem_contact_reborn#18]
If there are any blockers to a new beta release, let's lost them here. Otherwise I'm keen to see a beta of the revamped version for user testing and feedback.

**Comment by Bloke** [comment]
None as far as I'm aware. Did the new radio button stuff hold up OK in your tests?

**Comment by philwareham** [comment]
I'll test it today - haven't had a chance last few days - will let you know.

**Comment by philwareham** [comment]
Can you mail me a new compile of the plugin, so I can test changes and evaluate what (if anything) we need to do to improve radio buttons? Cheers!

**Comment by philwareham** [comment]
Fairly happy to go to beta now, if you want to? We can thrash out the radio button functionality during the beta if you like. Everything else I've tested and think works as intended.

**Comment by philwareham** [comment]
Any news on a compiled beta plugin of this? Cheers!

**Comment by Bloke** [comment]
I have one report to chase down. Perhaps you can corroborate if it's misbehaving for you. This is what was said via email:

If the form validates with errors, the class "zemRequired" no longer switches to "zemRequirederrorElement".

Haven't had a chance to check it out yet. If it's broken, an issue needs raising and I'll squash it.

**Comment by philwareham** [comment]
To be honest, the classname situation was a bit messy so maybe I changed it in a commit (can't remember now). Classnames shouldn't switch from one thing to another in my opinion. Rather, an additional class should be applied, keeping the original classname in place.

So, for example - non-error state on a required field:

    class="zemRequired"

Error state:

    class="zemRequired errorEelement"

Otherwise, if I have placed a hook on `zemRequired` and that changes to `zemRequirederrorlement` I've lost my hook or have to repeat my CSS rule for the additional class. That is not very DRY.

**Comment by Bloke** [comment]
I concur. Does errorElement get added? I thought it did, but maybe I'm going senile.

**Comment by philwareham** [comment]
It does get added. Just done a PR to remove any mentions of `zemRequirederrorElement`.

**Comment by philwareham** [comment]
Bumping this - can you do a compiled beta release Stef?

**Comment by Bloke** [comment]
Yes. I need to find a way to address a concern about the way required is used and haven't found a decent solution yet. But for the time being I'll issue this as a beta and open a new forum thread. Will do that later when I get a chance.

**Comment by philwareham** [comment]
Beta released, closing
