### ISSUE TITLE
Remove unused classes completely if desired

### ISSUE THREAD

**Issue by philwareham** [Bloke/zem_contact_reborn#19]
An author should be able to remove classes from elements if desired (apart from ones such as `zemRequired` which are necessary).

Consider this tag code:

    <txp:zem_contact_text class="" name="company" size="32" label="Company" required="0" />

Which **correctly** renders this code:

    <label for="company">Company</label><br>
    <input id="company" name="company" type="text" size="32" maxlength="100">

Now this tag code (with the field set to required):

    <txp:zem_contact_text class="" name="company" size="32" label="Company" required="1" />

Which **incorrectly** renders this HTML code:

    <label for="company" class="zemRequired company">Company</label><br>
    <input class="zemRequired" id="company" name="company" type="text" size="32" maxlength="100">

An extra class has been added, that we don't want (the `company` class). The author wanted this really:

    <label for="company" class="zemRequired">Company</label><br>
    <input class="zemRequired" id="company" name="company" type="text" size="32" maxlength="100">

In the interest of backwards compatibilty, I don't mind that extra class being there as a default - but if an author stipulates `class=""` then it should be removed for them.

**Comment by Bloke** [comment]
Easiest route is to remove `$name` from all label class attributes entirely. Honestly, I don't know why it's there. Can you think of a good reason why anyone would need it?

The only historical reason I can think of is that the class was applied to both label and input control, so the entire widget could be targeted directly with a single class if you knew the name you assigned to it. Now, however, the `$name` is missing from the input control, so having it only on the label is of questionable value anyway.

Am I missing anything here? Is there any point adding extra code to maintain two separate class lists (one with the `$name` for labels, and one without for the input control) or can we just do away with it entirely?

Radios are an exception right now: they enforce the `$name` on both label and input widget. Is that correct behaviour or can it be dropped here too?

**Comment by philwareham** [comment]
Personally I would do away with it completely, but I was unsure how that would affect current users if they have hooked into any of the classnames.

It was a bad design choice, not least because it could introduce the risk of unintended classname clashes. I'd remove if we can.

**Comment by Bloke** [comment]
I'll ditch it then.
