### ISSUE TITLE
HTML5 form input type: date validation fails

### ISSUE THREAD

**Issue by renejackowski** [Bloke/zem_contact_reborn#2]
When setup a form with the HTML5 input type="date" and you are on an iDevice with native datepicker, the date won’t be validated. After submit ZCR says »Required field missing«, even though the date is in there. This is NOT Txp’s prefs (posted / archive dates) related.

TXP: 4.5.7
ZCR: 4.5.0.0

**Comment by Bloke** [comment]
Presumed fixed. Reopen if this is not the case.

**Comment by renejackowski** [comment]
Hi Stef!

Many thx for this, will check this next days.
But, is there some compiled version of this plugin to paste it into plugin page?


-- 
Mit besten Gr��en aus Morbach
Ren� Jackowski (Inhaber)
---------------------------------------------------

VivaLaJack.de
graphic design | web development

Bernkasteler Stra�e 6
54497 Morbach

Telefon: 0 65 33 . 9 57 43 50
Telefax: 0 65 33 . 9 57 43 55

Website: http://vivalajack.de/
Twitter: https://twitter.com/vivalajack_de

---------------------------------------------------
VivaLaJack.de ist ein kleines Grafik- und Webstudio
f�r ma�geschneiderte Kommunikation.



Am 05.03.2015 um 11:33 schrieb Stef Dawson <notifications@github.com>:
