### ISSUE TITLE
Select tag - remove attribute size="0" default

### ISSUE THREAD

**Issue by philwareham** [Bloke/zem_contact_reborn#21]
If a user doesn't supply a `size` attribute for zem_contact_select, then the HTML output includes the attribute `size="0"`. This is *technically* incorrect, as in the HTML5 spec it states it should be `1` - but it's safer to omit the `size` attribute altogether in this instance and let browsers use their default rendering, due to browsers not adhering property to the spec.

From MDN:

"According to the HTML5 specification, the default value for size should be 1; however, in practice, this has been found to break some web sites, and no other browser currently does that, so Mozilla have opted to continue to return 0 for the time being with Firefox."

**Comment by Bloke** [comment]
Good catch. Will fix, thanks.
