### ISSUE TITLE
Checkboxes and radios - option to have label before

### ISSUE THREAD

**Issue by philwareham** [Bloke/zem_contact_reborn#22]
It would be nice to have the option of rendering the label tag *before* the checkbox/radio, as an alternative to rendering label after. There are situations where this can be useful. Would need a new attribute.

I guess that new attribute could also be allowed on other input/select/textarea tags too, for more flexibility in how an author wants to display their forms (although with the reverse default setting).

**Comment by Bloke** [comment]
Makes sense to introduce a new attribute for this, across the board. Any preference for the name of it? Presumably this would also benefit RTL languages so I'd probably shy away from the notion of `label_first` and such like. Unless the default setting could be language dependent somehow so "first" means "left" for LTR but "right" for RTL...? Or is that opening up a world of hurt?

**Comment by philwareham** [comment]
Hmmm, how about `label_position` attribute and `before/after` as the values.

It doesn't make any difference for RTL languages, since the browser automatically flips the rendering anyway if a `dir=rtl` is used. So for them label after is still label after, just the reverse logic of how we (as LTR language speakers) read. So this is perfectly safe to do.

**Comment by Bloke** [comment]
I didn't know that about browsers and RTL: handy to know, thanks. `label_position` makes sense. Leave it with me.

**Comment by Bloke** [comment]
Closed by ac371c4b1c9c243a975d4d897c70a21ad5f20603
