### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by renejackowski** [Bloke/zem_contact_reborn#3]
E.g. fill out a form, and (what be can happen) forget one required field. Submit the form. The form would be validated and return the required fields (on best practices) highlighted. Now look on the other fields you filled out before, they are all validated as OK, but they are now empty. So, the form forgets the filled fields. Further, you know the occurring unintended side effects…

TXP: 4.5.7
ZCR: 4.5.0.0

**Comment by Bloke** [comment]
I cannot replicate this. It may have been a bug that's now fixed.

If the problem persists, please reopen the issue with some example code and input.
