### ISSUE TITLE
"unregistered_tag while parsing form None on page contact"

### ISSUE THREAD

**Issue by bts368** [Bloke/zem_contact_reborn#32]
apologies if this is fixed in master, i'm using the 4.5.0 release.

getting a ton of these on page load:
______________________________________
Tag error: <txp:zem_contact to="info@sysadministrivia.com"> ->  Textpattern Notice: unregistered_tag while parsing form None on page contact

textpattern/lib/txplib_publish.php:467 trigger_error()
textpattern/lib/txplib_publish.php:391 processTags()
textpattern/lib/txplib_misc.php:4358 parse()
textpattern/publish.php:558 parse_page()
index.php:105 textpattern()

Tag error: <txp:zem_contact_text break="" label="Name: " /> ->  Textpattern Notice: unregistered_tag while parsing form None on page contact

textpattern/lib/txplib_publish.php:467 trigger_error()
textpattern/lib/txplib_publish.php:382 processTags()
textpattern/lib/txplib_misc.php(1783) : eval()'d code:114 parse()
zem_contact()
textpattern/vendors/Textpattern/Tag/Registry.php:83 call_user_func()
textpattern/lib/txplib_publish.php:468 Textpattern\Tag\Registry->process()
textpattern/lib/txplib_publish.php:391 processTags()
textpattern/lib/txplib_misc.php:4358 parse()
textpattern/publish.php:558 parse_page()
index.php:105 textpattern()

Tag error: <txp:zem_contact_email label="Email: " break="" /> ->  Textpattern Notice: unregistered_tag while parsing form None on page contact

textpattern/lib/txplib_publish.php:467 trigger_error()
textpattern/lib/txplib_publish.php:382 processTags()
textpattern/lib/txplib_misc.php(1783) : eval()'d code:114 parse()
zem_contact()
textpattern/vendors/Textpattern/Tag/Registry.php:83 call_user_func()
textpattern/lib/txplib_publish.php:468 Textpattern\Tag\Registry->process()
textpattern/lib/txplib_publish.php:391 processTags()
textpattern/lib/txplib_misc.php:4358 parse()
textpattern/publish.php:558 parse_page()
index.php:105 textpattern()

Tag error: <txp:zem_contact_textarea cols="30" rows="10" label="Feedback/Comment/Bribery" /> ->  Textpattern Notice: unregistered_tag while parsing form None on page contact

textpattern/lib/txplib_publish.php:467 trigger_error()
textpattern/lib/txplib_publish.php:382 processTags()
textpattern/lib/txplib_misc.php(1783) : eval()'d code:114 parse()
zem_contact()
textpattern/vendors/Textpattern/Tag/Registry.php:83 call_user_func()
textpattern/lib/txplib_publish.php:468 Textpattern\Tag\Registry->process()
textpattern/lib/txplib_publish.php:391 processTags()
textpattern/lib/txplib_misc.php:4358 parse()
textpattern/publish.php:558 parse_page()
index.php:105 textpattern()

Tag error: <txp:zem_contact_checkbox label="Yes, please send; I am a meat popsicle." /> ->  Textpattern Notice: unregistered_tag while parsing form None on page contact

textpattern/lib/txplib_publish.php:467 trigger_error()
textpattern/lib/txplib_publish.php:382 processTags()
textpattern/lib/txplib_misc.php(1783) : eval()'d code:114 parse()
zem_contact()
textpattern/vendors/Textpattern/Tag/Registry.php:83 call_user_func()
textpattern/lib/txplib_publish.php:468 Textpattern\Tag\Registry->process()
textpattern/lib/txplib_publish.php:391 processTags()
textpattern/lib/txplib_misc.php:4358 parse()
textpattern/publish.php:558 parse_page()
index.php:105 textpattern()

Tag error: <txp:zem_contact_serverinfo name="REMOTE_ADDR" label="IP number" /> ->  Textpattern Notice: unregistered_tag while parsing form None on page contact

textpattern/lib/txplib_publish.php:467 trigger_error()
textpattern/lib/txplib_publish.php:382 processTags()
textpattern/lib/txplib_misc.php(1783) : eval()'d code:114 parse()
zem_contact()
textpattern/vendors/Textpattern/Tag/Registry.php:83 call_user_func()
textpattern/lib/txplib_publish.php:468 Textpattern\Tag\Registry->process()
textpattern/lib/txplib_publish.php:391 processTags()
textpattern/lib/txplib_misc.php:4358 parse()
textpattern/publish.php:558 parse_page()
index.php:105 textpattern()

Tag error: <txp:zem_contact_submit label="Send" /> ->  Textpattern Notice: unregistered_tag while parsing form None on page contact

textpattern/lib/txplib_publish.php:467 trigger_error()
textpattern/lib/txplib_publish.php:382 processTags()
textpattern/lib/txplib_misc.php(1783) : eval()'d code:114 parse()
zem_contact()
textpattern/vendors/Textpattern/Tag/Registry.php:83 call_user_func()
textpattern/lib/txplib_publish.php:468 Textpattern\Tag\Registry->process()
textpattern/lib/txplib_publish.php:391 processTags()
textpattern/lib/txplib_misc.php:4358 parse()
textpattern/publish.php:558 parse_page()
index.php:105 textpattern()
______________________________________

(didn't even bother formatting, sorry.)

using this:
```
<txp:zem_contact to="info@sysadministrivia.com">
  <txp:zem_contact_text break="" label="Name: " /><br>
  <txp:zem_contact_email label="Email: " break="" /><br>
  <txp:zem_contact_textarea cols="30" rows="10" label="Feedback/Comment/Bribery" />
  <br>
  <txp:zem_contact_checkbox label="Yes, please send; I am a meat popsicle." />
  <txp:zem_contact_serverinfo name="REMOTE_ADDR" label="IP number" />
  <txp:zem_contact_serverinfo name="REMOTE_PORT" label="SRC port" />
  <txp:zem_contact_serverinfo name="X_FORWARDED_FOR" label="X_FORWARDED" />
  <txp:zem_contact_serverinfo name="SERVER_NAME" label="VHOST" />
  <txp:zem_contact_serverinfo name="HTTP_REFERER" label="Referer" />
  <txp:zem_contact_serverinfo name="HTTP_USER_AGENT" label="UA string" />
  <txp:zem_contact_serverinfo name="HTTPS" label="HTTPS bool" />
  <txp:zem_contact_submit label="Send" />
</txp:zem_contact>
```

Interestingly enough, the form sends just fine (and all the fields are populated when they should be with what they should be, etc.) so it doesn't seem to be fatal, but i figured i'd pass it along.

(this is on the "4.6.x" "version" of TXP- specifically, current HEAD- 6083763540f3a1cbcc9620d5eb307ccbc8b50ece ) on nginx 1.9.10 with php-fpm, on php 7.0.3 (via Arch).

you did a GREAT job on reviving this plugin, by the way!

**Comment by Bloke** [comment]
Fixed by 09cf870d88d92e73320ffa3d9799c3125309a57b
