### ISSUE TITLE
Validation issue with `zem_contact_select`

### ISSUE THREAD

**Issue by phiw13** [Bloke/zem_contact_reborn#36]
Given this input: `<txp:zem_contact_select label="Department" options=",Marketing,Sales,Support" />`

This generates the following html (given an HTML5 Doctype)

```
<select class="zemSelect required-field" id="Department" name="Department" form="zcr980d3c953e3927933e7094318b520118" required="">
	<option selected="selected"> </option>
	<option>Marketing</option>
	<option>Sales</option>
	<option>Support</option>
</select>
```

The HTML validator flags the first option as invalid:
“Element option without attribute label must not be empty.“

(No I didn’t know that either)

Note:
1. none of the options have a `label` or `value` attribute (not required nowadays…, go figure)
2. trying to validate the above HTML (manually generated) with one change `<option selected="selected" label=""> </option>` (added empty label attribute) gives the same result. But `label=" "` does work (contains a space).

**Comment by Bloke** [comment]
Fixed via 9d994f790c254d428677568cd53a2b194adbb8de

**Comment by phiw13** [comment]
Are you sure this is fully fixed ? I updated to the latest come with the help of plugin composer.

under ZCR beta 3 I could do 

input

```
<div class="contact-subject"><txp:zem_contact_select class="" break="" label="Subject" name="subject">
<txp:zem_contact_option class="" label=" " value="" />
<txp:zem_contact_option class="" label="General enquiry" value="General enquiry" />
<txp:zem_contact_option class="" label="Site issue" value="Site issue" />
<txp:zem_contact_option class="" label="Other…" value="Other…" />
</txp:zem_contact_select></div>
```

output (valid !):

```
<div class="contact-subject"><label for="subject" class="required-field">Subject</label>
<select class="required-field" id="subject" name="subject" form="zcr7870354b33b638936ebd73597f8ead8d" required="">
<option selected label=" "></option>
<option label="General enquiry" value="General enquiry"></option>
<option label="Site issue" value="Site issue"></option>
<option label="Other…" value="Other…"></option>
</select></div>
```

with the latest code, the output I get is:

```
<div class="contact-subject"><label for="subject" class="required-field">Subject</label>
<select class="required-field" id="subject" name="subject" form="zcr7870354b33b638936ebd73597f8ead8d" required="">
<option value=" "> </option>
<option label="General enquiry" value="General enquiry"></option>
<option label="Site issue" value="Site issue"></option>
<option label="Other…" value="Other…"></option>
</select></div>
```

which the validator rejects. No matter what combination of `label` and `value` I put on the first (empty) option element, I cannot get something that pleases the validator, which would be

`<option label=" "></option>` or `<option label=" " value=""></option>`

Test page:
http://dev.l-c-n.com/_temp2/contact-test.html
(contains one select as generated by ZRC, the second one is the ‘ideal’ output)

**Comment by Bloke** [comment]
Weird, with your exact input from above pasted into my latest dev version that mirrors the GitHub repo, this is the HTML I get:

```
<div class="contact-subject"><label for="subject" class="zemRequired">Subject</label>
<select class="zemRequired" id="subject" name="subject" form="zcref1a577faab305de7f12b87359aa856a" required>
<option value=" "> </option>
<option value="General enquiry">General enquiry</option>
<option value="Site issue">Site issue</option>
<option value="Other…">Other…</option>
</select></div>
```

Which I believe is valid. What's going on?!

**Comment by phiw13** [comment]
The validator thinks it should be  `<option label=" "> </option>`

the whole text is rather hard to read and obscure I must say.
http://www.w3.org/TR/html5/forms.html#the-select-element

The first select in my test file linked above, which is  straight copy/paste from ZCR doesn’t pass, the second one does (manually edited)
https://validator.w3.org/nu/?doc=http%3A%2F%2Fdev.l-c-n.com%2F_temp2%2Fcontact-test.html
