### ISSUE TITLE
Consider adding the `aria-invalid` attribute on invalid required fields

### ISSUE THREAD

**Issue by phiw13** [Bloke/zem_contact_reborn#37]
Details [in the spec here](http://www.w3.org/TR/wai-aria-1.1/#aria-invalid).

Basically, when the form is submitted and contains errors in required fields, ZCR already flag these fields with an error message (and an a CSS `.class`). Adding the `aria-invalid` attribute might make it easier for users of AT to find the field, particularly for complex forms.

Output would be something like:

```
<input class="zemText required-field warn-field" id="Name" name="Name" type="text"
 maxlength="100" form="zcr90ee6dd232899193473d48838f53e9b7" 
placeholder="Your Name" required aria-invalid="true">
```

**Comment by Bloke** [comment]
Closed (mostly) via fe95e6af5941bcc591bf770b6eb9aaf6305446f5.

Radio sets might have to be the exception. Solution: make sure one is always checked by default.
