### ISSUE TITLE
add support for the `novalidate` attribute on the form element

### ISSUE THREAD

**Issue by phiw13** [Bloke/zem_contact_reborn#38]
The attribute, when present on the @form@ element prevent the automatic validation of `required` fields by some browsers.  For the details see [this MDN article](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms_in_HTML#Constraint_Validation)

See also this[ forum post](http://forum.textpattern.com/viewtopic.php?pid=299216#p299216)

**Comment by Bloke** [comment]
Closed via c29e4e8ca3c4f23529e2464bb63e444c7722672b
