### ISSUE TITLE
fieldset and legend on output even when label attr set to empty value

### ISSUE THREAD

**Issue by maniqui** [Bloke/zem_contact_reborn#41]
Plugin FAQ section states:

> How do I remove the legend and fieldset surrounding the contact form?
> Set the `label` attribute to an empty value (`label=""`) in the `zem_contact` tag.

And also, help for `<txp:zem_contact />` tag states:

> `label="text"`
> Label for the contact form. If set to an empty string, display of the fieldset and legend tags will be suppressed. Default is Contact.

But logic seems flawed:

```php
    // Set defaults, in the local language if necessary.
    if ($label === '') {
        $label = gTxt('zem_contact_contact');
    }
```

as setting the attribute to an empty value, it always gets populated by some string.

I've tried setting the attribute to a blank space (`label=" "`) but the `fieldset` and `legend` tags (even if the latter is empty) are part of the output.

**Comment by Bloke** [comment]
Good catch. I should probably change the default to null and test that instead of an empty string. I'll look into it.

**Comment by Bloke** [comment]
Wait, I've already [fixed this](https://github.com/Bloke/zem_contact_reborn/commit/02a8590c2e4b81d43cad53f1ac00e5c169dafa0b). It just hasn't made it into an official release yet. I'll close this and package up a release at some point.
